### ISSUE TITLE
Feature: Login

### ISSUE THREAD

**Issue by selvianu** [fresher-batch-2021/lmsapp-angular#2]
User Story: With valid login credentials, user should be able login
Even after registration, it shows error

![image](https://user-images.githubusercontent.com/22638364/130776890-466a2ec7-fb02-4faf-ba9c-dfbc93255276.png)

**Comment by Renis8903** [comment]
Now I am Accepted your Request Now you can Access my Application
username : riya@gmail.com
password : 9513Riya
